project:
  type: website
  output-dir: docs
  render: markdown

website:
  title: "Météo à Montpellier"
  page-navigation: true
  repo-url: https://github.com/Qufst/projet-personnel-mto
  repo-actions: [source, issue]
  
  navbar:
    tools: 
      - icon: github
        href: https://github.com/Qufst/projet-personnel-mto
        text: GitHub
    left:
      - href: tableaumeteopy.qmd
        text: Home

      

        
execute:
  echo: false          


format:
  html:
    theme: cosmo
    css: style.css
    toc: false
jupyter: python3