
execute:
  echo: false          

project:
  type: website
  output-dir: docs
website:
  title: "Météo à Montpellier"
  navbar:
    tools: 
      - icon: github
        href: https://github.com/Qufst/projet-personnel-mto
        text: GitHub
    left:
      - href: tableaumeteopy.qmd
        text: Prévisions
format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: style.css
    toc: true
    page-layout: full

editor: visual