name: Actualiser le site

on:
  schedule:
      - cron: '0 6,12,18,23 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Quarto
        run: |
          pip install quarto

      - name: Actualiser le site avec Quarto
        run: |
          quarto render tableaumeteopy.qmd

