name: Actualiser le site

on:
  schedule:
      - cron: '44 22 * * *'
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python et dependancies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"
          cache: "pip"
      - run: python3 -m pip install jupyter
      - run: python3 -m pip install -r exigences.txt

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Actualiser le site avec Quarto
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

